// Generated by `ledger units` from the files in this folder; do not edit.
#![allow(clippy::module_inception)]

pub mod debugtext;
pub mod font;
pub mod menu;
pub mod radialtile;
pub mod run_00a1c340;
pub mod run_00a1eeb0;
pub mod tile;
pub mod tile3d;
pub mod tileimage;
pub mod tilemenu;
pub mod tilerect;
pub mod tiletext;
pub mod xuserinterface;

pub fn funcs(out: &mut Vec<(u32, crate::AbiFn)>) {
    out.extend(debugtext::funcs());
    out.extend(font::funcs());
    out.extend(menu::funcs());
    out.extend(radialtile::funcs());
    out.extend(run_00a1c340::funcs());
    out.extend(run_00a1eeb0::funcs());
    out.extend(tile::funcs());
    out.extend(tile3d::funcs());
    out.extend(tileimage::funcs());
    out.extend(tilemenu::funcs());
    out.extend(tilerect::funcs());
    out.extend(tiletext::funcs());
    out.extend(xuserinterface::funcs());
}
