// Generated by `ledger units` from the files in this folder; do not edit.
#![allow(clippy::module_inception)]

pub mod atmosphere;
pub mod clouds;
pub mod moon;
pub mod precipitation;
pub mod run_00633b40;
pub mod run_00633c90;
pub mod run_006366b0;
pub mod run_006368f0;
pub mod run_00639ce0;
pub mod run_0063f790;
pub mod run_0063fb70;
pub mod run_006404b0;
pub mod sky;
pub mod skyobject;
pub mod skytexturemanager;
pub mod stars;
pub mod sun;

pub fn funcs(out: &mut Vec<(u32, crate::AbiFn)>) {
    out.extend(atmosphere::funcs());
    out.extend(clouds::funcs());
    out.extend(moon::funcs());
    out.extend(precipitation::funcs());
    out.extend(run_00633b40::funcs());
    out.extend(run_00633c90::funcs());
    out.extend(run_006366b0::funcs());
    out.extend(run_006368f0::funcs());
    out.extend(run_00639ce0::funcs());
    out.extend(run_0063f790::funcs());
    out.extend(run_0063fb70::funcs());
    out.extend(run_006404b0::funcs());
    out.extend(sky::funcs());
    out.extend(skyobject::funcs());
    out.extend(skytexturemanager::funcs());
    out.extend(stars::funcs());
    out.extend(sun::funcs());
}
