// Generated by `ledger units` from the files in this folder; do not edit.
#![allow(clippy::module_inception)]

pub mod alchemyitem;
pub mod effectarchetype;
pub mod effectitem;
pub mod effectitemlist;
pub mod effectsetting;
pub mod effectsettingcollection;
pub mod enchantmentitem;
pub mod ingredientitem;
pub mod magicformulas;
pub mod magicitem;
pub mod magicitemobject;
pub mod magicsystem;
pub mod run_00402bc0;
pub mod run_00402d00;
pub mod run_00403720;
pub mod run_00403b30;
pub mod run_00406f60;
pub mod run_00408b20;
pub mod run_00409060;
pub mod run_004098d0;
pub mod run_00409da0;
pub mod run_0040c0e0;
pub mod run_0040ca10;
pub mod run_0040dee0;
pub mod spellitem;

pub fn funcs(out: &mut Vec<(u32, crate::AbiFn)>) {
    out.extend(alchemyitem::funcs());
    out.extend(effectarchetype::funcs());
    out.extend(effectitem::funcs());
    out.extend(effectitemlist::funcs());
    out.extend(effectsetting::funcs());
    out.extend(effectsettingcollection::funcs());
    out.extend(enchantmentitem::funcs());
    out.extend(ingredientitem::funcs());
    out.extend(magicformulas::funcs());
    out.extend(magicitem::funcs());
    out.extend(magicitemobject::funcs());
    out.extend(magicsystem::funcs());
    out.extend(run_00402bc0::funcs());
    out.extend(run_00402d00::funcs());
    out.extend(run_00403720::funcs());
    out.extend(run_00403b30::funcs());
    out.extend(run_00406f60::funcs());
    out.extend(run_00408b20::funcs());
    out.extend(run_00409060::funcs());
    out.extend(run_004098d0::funcs());
    out.extend(run_00409da0::funcs());
    out.extend(run_0040c0e0::funcs());
    out.extend(run_0040ca10::funcs());
    out.extend(run_0040dee0::funcs());
    out.extend(spellitem::funcs());
}
