// Generated by `ledger units` from the files in this folder; do not edit.
#![allow(clippy::module_inception)]

pub mod run_004f15a0;
pub mod run_004f1ed0;
pub mod run_004f2480;
pub mod run_004f32e0;
pub mod run_004f3610;
pub mod run_004f4280;
pub mod run_004f5040;
pub mod run_004f5d90;
pub mod run_004f5e80;
pub mod run_004f6de0;
pub mod run_004f7030;
pub mod tesregion;
pub mod tesregiondata;
pub mod tesregiondatagrass;
pub mod tesregiondataimposter;
pub mod tesregiondatalandscape;
pub mod tesregiondatalist;
pub mod tesregiondatamanager;
pub mod tesregiondatamap;
pub mod tesregiondatasound;
pub mod tesregiondataweather;
pub mod tesregiongrassobject;
pub mod tesregiongrassobjectlist;
pub mod tesregionlist;
pub mod tesregionpoint;
pub mod tesregionpointlist;

pub fn funcs(out: &mut Vec<(u32, crate::AbiFn)>) {
    out.extend(run_004f15a0::funcs());
    out.extend(run_004f1ed0::funcs());
    out.extend(run_004f2480::funcs());
    out.extend(run_004f32e0::funcs());
    out.extend(run_004f3610::funcs());
    out.extend(run_004f4280::funcs());
    out.extend(run_004f5040::funcs());
    out.extend(run_004f5d90::funcs());
    out.extend(run_004f5e80::funcs());
    out.extend(run_004f6de0::funcs());
    out.extend(run_004f7030::funcs());
    out.extend(tesregion::funcs());
    out.extend(tesregiondata::funcs());
    out.extend(tesregiondatagrass::funcs());
    out.extend(tesregiondataimposter::funcs());
    out.extend(tesregiondatalandscape::funcs());
    out.extend(tesregiondatalist::funcs());
    out.extend(tesregiondatamanager::funcs());
    out.extend(tesregiondatamap::funcs());
    out.extend(tesregiondatasound::funcs());
    out.extend(tesregiondataweather::funcs());
    out.extend(tesregiongrassobject::funcs());
    out.extend(tesregiongrassobjectlist::funcs());
    out.extend(tesregionlist::funcs());
    out.extend(tesregionpoint::funcs());
    out.extend(tesregionpointlist::funcs());
}
