//! The unit tree of `crates/engine/src/units` (docs/ENGINE_CRATE.md).
//!
//! One file per source unit of the engine map, in one folder per subsystem:
//! `fallout/ai/processlists.cpp` → `units/fallout_ai/processlists.rs`.
//! The `mod.rs` files are generated from the files present (`units`), so
//! translators only ever edit their own unit files.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

const KEYWORDS: &[&str] = &[
    "as", "async", "await", "box", "break", "const", "continue", "crate", "dyn", "else", "enum",
    "extern", "false", "fn", "for", "gen", "if", "impl", "in", "let", "loop", "match", "mod",
    "move", "mut", "priv", "pub", "ref", "return", "self", "static", "struct", "super", "trait",
    "true", "try", "type", "unsafe", "use", "where", "while", "yield", "abstract", "become",
    "do", "final", "macro", "override", "typeof", "unsized", "virtual",
];

/// A Rust module name from a path piece.
pub fn ident(s: &str) -> String {
    let mut out = String::new();
    for c in s.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_lowercase());
        } else if !out.ends_with('_') {
            out.push('_');
        }
    }
    let out = out.trim_matches('_').to_string();
    if out.is_empty() || out.starts_with(|c: char| c.is_ascii_digit()) || KEYWORDS.contains(&out.as_str()) {
        format!("u_{out}")
    } else {
        out
    }
}

/// (subsystem folder, file stem) of a unit from the map.
pub fn module_of(unit: &str, subsystem: &str) -> (String, String) {
    let file = unit.rsplit('/').next().unwrap_or(unit);
    let stem = file.rsplit_once('.').map(|(a, _)| a).unwrap_or(file);
    (ident(subsystem), ident(stem))
}

const HEADER: &str = "// Generated by `ledger units` from the files in this folder; do not edit.\n";

/// Regenerates every `mod.rs` under `units` (the hand-written
/// `platform.rs` and any other top-level file are kept as modules).
pub fn regenerate(units: &Path) -> Result<usize, String> {
    let mut subs: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let mut top: Vec<String> = Vec::new();
    let rd = fs::read_dir(units).map_err(|e| format!("{}: {e}", units.display()))?;
    for e in rd.flatten() {
        let p = e.path();
        let name = e.file_name().to_string_lossy().to_string();
        if p.is_dir() {
            let mut files = Vec::new();
            for f in fs::read_dir(&p).map_err(|e| e.to_string())?.flatten() {
                let n = f.file_name().to_string_lossy().to_string();
                if let Some(stem) = n.strip_suffix(".rs") {
                    if stem != "mod" {
                        files.push(stem.to_string());
                    }
                }
            }
            files.sort();
            subs.insert(name, files);
        } else if let Some(stem) = name.strip_suffix(".rs") {
            if stem != "mod" {
                top.push(stem.to_string());
            }
        }
    }
    top.sort();
    let mut n = 0;
    for (sub, files) in &subs {
        let mut s = String::from(HEADER);
        for f in files {
            let _ = writeln!(s, "pub mod {f};");
        }
        let _ = writeln!(s, "\npub fn funcs(out: &mut Vec<(u32, crate::AbiFn)>) {{");
        for f in files {
            let _ = writeln!(s, "    out.extend({f}::funcs());");
        }
        let _ = writeln!(s, "}}");
        write_if_changed(&units.join(sub).join("mod.rs"), &s)?;
        n += files.len();
    }
    let mut s = String::from(HEADER);
    s.push_str("//! Translated units, one folder per subsystem (docs/ENGINE_CRATE.md).\n\n");
    let mut mods: Vec<&String> = top.iter().chain(subs.keys()).collect();
    mods.sort();
    for m in mods {
        let _ = writeln!(s, "pub mod {m};");
    }
    let _ = writeln!(s, "\n/// Every registered function of every unit.");
    let _ = writeln!(s, "pub fn funcs(out: &mut Vec<(u32, crate::AbiFn)>) {{");
    for t in &top {
        let _ = writeln!(s, "    out.extend({t}::funcs());");
    }
    for sub in subs.keys() {
        let _ = writeln!(s, "    {sub}::funcs(out);");
    }
    let _ = writeln!(s, "}}");
    write_if_changed(&units.join("mod.rs"), &s)?;
    Ok(n + top.len())
}

fn write_if_changed(p: &Path, s: &str) -> Result<(), String> {
    if fs::read_to_string(p).ok().as_deref() == Some(s) {
        return Ok(());
    }
    fs::write(p, s).map_err(|e| format!("{}: {e}", p.display()))
}

/// Creates the file of a unit if it does not exist yet. Returns its path
/// relative to `units`.
pub fn scaffold(units: &Path, unit: &str, subsystem: &str) -> Result<String, String> {
    let (sub, stem) = module_of(unit, subsystem);
    let dir = units.join(&sub);
    fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    let file = dir.join(format!("{stem}.rs"));
    let rel = format!("{sub}/{stem}.rs");
    if file.exists() {
        return Ok(rel);
    }
    let s = format!(
        "//! `{unit}` (Xbox PDB source unit), subsystem `{subsystem}`: its functions in\n\
         //! FalloutNV.exe 1.4.0.525, translated (docs/ENGINE_CRATE.md).\n\
         \n\
         #[allow(unused_imports)]\n\
         use crate::prelude::*;\n\
         \n\
         /// This unit's translated functions, by exe address.\n\
         pub fn funcs() -> Vec<(u32, AbiFn)> {{\n    vec![]\n}}\n"
    );
    fs::write(&file, s).map_err(|e| format!("{}: {e}", file.display()))?;
    Ok(rel)
}
