// Generated by `ledger units` from the files in this folder; do not edit.
#![allow(clippy::module_inception)]

pub mod bstreemanager;
pub mod bstreemodel;
pub mod bstreenode;
pub mod run_006662a0;
pub mod run_0066b0b0;

pub fn funcs(out: &mut Vec<(u32, crate::AbiFn)>) {
    out.extend(bstreemanager::funcs());
    out.extend(bstreemodel::funcs());
    out.extend(bstreenode::funcs());
    out.extend(run_006662a0::funcs());
    out.extend(run_0066b0b0::funcs());
}
