// Generated by `ledger units` from the files in this folder; do not edit.
#![allow(clippy::module_inception)]

pub mod bsaudio;
pub mod bsaudiomanager;
pub mod bsgamesound;
pub mod bssoundhandle;
pub mod bsxenonaudio;
pub mod bsxenonaudiolistener;
pub mod run_00ad8790;
pub mod run_00ae91f0;
pub mod run_00aea020;
pub mod run_00aea4d0;
pub mod run_00aea5c0;
pub mod run_00aea770;

pub fn funcs(out: &mut Vec<(u32, crate::AbiFn)>) {
    out.extend(bsaudio::funcs());
    out.extend(bsaudiomanager::funcs());
    out.extend(bsgamesound::funcs());
    out.extend(bssoundhandle::funcs());
    out.extend(bsxenonaudio::funcs());
    out.extend(bsxenonaudiolistener::funcs());
    out.extend(run_00ad8790::funcs());
    out.extend(run_00ae91f0::funcs());
    out.extend(run_00aea020::funcs());
    out.extend(run_00aea4d0::funcs());
    out.extend(run_00aea5c0::funcs());
    out.extend(run_00aea770::funcs());
}
