// Generated by `ledger units` from the files in this folder; do not edit.
#![allow(clippy::module_inception)]

pub mod falloutaudio;
pub mod falloutaudiomedia;
pub mod falloutradio;
pub mod impactmixer;
pub mod run_0082f140;
pub mod run_0082f760;
pub mod run_00831e00;
pub mod run_00831eb0;
pub mod run_008373f0;
pub mod run_008374e0;

pub fn funcs(out: &mut Vec<(u32, crate::AbiFn)>) {
    out.extend(falloutaudio::funcs());
    out.extend(falloutaudiomedia::funcs());
    out.extend(falloutradio::funcs());
    out.extend(impactmixer::funcs());
    out.extend(run_0082f140::funcs());
    out.extend(run_0082f760::funcs());
    out.extend(run_00831e00::funcs());
    out.extend(run_00831eb0::funcs());
    out.extend(run_008373f0::funcs());
    out.extend(run_008374e0::funcs());
}
