// Generated by `ledger units` from the files in this folder; do not edit.
//! Translated units, one folder per subsystem (docs/ENGINE_CRATE.md).

pub mod fallout_misc;
pub mod platform;

/// Every registered function of every unit.
pub fn funcs(out: &mut Vec<(u32, crate::AbiFn)>) {
    out.extend(platform::funcs());
    fallout_misc::funcs(out);
}
