// Generated by `ledger units` from the files in this folder; do not edit.
//! Translated units, one folder per subsystem (docs/ENGINE_CRATE.md).

pub mod bsaudio;
pub mod bscore;
pub mod bshavok;
pub mod bsmain;
pub mod bsmenu;
pub mod facegen;
pub mod fallout_ai;
pub mod fallout_audio;
pub mod fallout_debug;
pub mod fallout_dialogue;
pub mod fallout_interface;
pub mod fallout_magic;
pub mod fallout_misc;
pub mod fallout_shared;
pub mod fallout_shared_distant_terrain_system;
pub mod fallout_shared_facegen;
pub mod fallout_shared_havok;
pub mod fallout_shared_magic;
pub mod fallout_shared_pathfinding;
pub mod fallout_shared_region_system;
pub mod fallout_shared_settings;
pub mod fallout_shared_sky;
pub mod fallout_shared_speedtree;
pub mod fallout_shared_tempeffects;
pub mod havok_sdk;
pub mod nianimation;
pub mod nicollision;
pub mod nimain;
pub mod niparticle;
pub mod nisystem;
pub mod platform;
pub mod unplaced;

/// Every registered function of every unit.
pub fn funcs(out: &mut Vec<(u32, crate::AbiFn)>) {
    out.extend(platform::funcs());
    bsaudio::funcs(out);
    bscore::funcs(out);
    bshavok::funcs(out);
    bsmain::funcs(out);
    bsmenu::funcs(out);
    facegen::funcs(out);
    fallout_ai::funcs(out);
    fallout_audio::funcs(out);
    fallout_debug::funcs(out);
    fallout_dialogue::funcs(out);
    fallout_interface::funcs(out);
    fallout_magic::funcs(out);
    fallout_misc::funcs(out);
    fallout_shared::funcs(out);
    fallout_shared_distant_terrain_system::funcs(out);
    fallout_shared_facegen::funcs(out);
    fallout_shared_havok::funcs(out);
    fallout_shared_magic::funcs(out);
    fallout_shared_pathfinding::funcs(out);
    fallout_shared_region_system::funcs(out);
    fallout_shared_settings::funcs(out);
    fallout_shared_sky::funcs(out);
    fallout_shared_speedtree::funcs(out);
    fallout_shared_tempeffects::funcs(out);
    havok_sdk::funcs(out);
    nianimation::funcs(out);
    nicollision::funcs(out);
    nimain::funcs(out);
    niparticle::funcs(out);
    nisystem::funcs(out);
    unplaced::funcs(out);
}
