// Generated by `ledger units` from the files in this folder; do not edit.
#![allow(clippy::module_inception)]

pub mod bgsdistantobjectblock;
pub mod bgsdistanttreeblock;
pub mod bgsterrainchunk;
pub mod bgsterrainmanager;
pub mod bgsterrainnode;
pub mod run_006fa160;
pub mod run_006fa210;
pub mod run_006fa6a0;
pub mod run_006faa30;
pub mod run_006fc490;
pub mod run_006fd010;

pub fn funcs(out: &mut Vec<(u32, crate::AbiFn)>) {
    out.extend(bgsdistantobjectblock::funcs());
    out.extend(bgsdistanttreeblock::funcs());
    out.extend(bgsterrainchunk::funcs());
    out.extend(bgsterrainmanager::funcs());
    out.extend(bgsterrainnode::funcs());
    out.extend(run_006fa160::funcs());
    out.extend(run_006fa210::funcs());
    out.extend(run_006fa6a0::funcs());
    out.extend(run_006faa30::funcs());
    out.extend(run_006fc490::funcs());
    out.extend(run_006fd010::funcs());
}
