// Generated by `ledger units` from the files in this folder; do not edit.
#![allow(clippy::module_inception)]

pub mod bstecreatetask;
pub mod bstempeffect;
pub mod bstempeffectdebris;
pub mod bstempeffectgeometrydecal;
pub mod bstempeffectparticle;
pub mod bstempeffectsimpledecal;
pub mod run_00682510;
pub mod run_0068a8d0;
pub mod run_0068ab60;

pub fn funcs(out: &mut Vec<(u32, crate::AbiFn)>) {
    out.extend(bstecreatetask::funcs());
    out.extend(bstempeffect::funcs());
    out.extend(bstempeffectdebris::funcs());
    out.extend(bstempeffectgeometrydecal::funcs());
    out.extend(bstempeffectparticle::funcs());
    out.extend(bstempeffectsimpledecal::funcs());
    out.extend(run_00682510::funcs());
    out.extend(run_0068a8d0::funcs());
    out.extend(run_0068ab60::funcs());
}
