// Generated by `ledger units` from the files in this folder; do not edit.
pub mod calendar;
pub mod garbagecollector;

pub fn funcs(out: &mut Vec<(u32, crate::AbiFn)>) {
    out.extend(calendar::funcs());
    out.extend(garbagecollector::funcs());
}
