// Generated by `ledger units` from the files in this folder; do not edit.
#![allow(clippy::module_inception)]

pub mod bsniallocator;
pub mod nibinarystream;
pub mod nifile;
pub mod nifilename;
pub mod nimemstream;
pub mod nipath;
pub mod nipath_xenon;
pub mod nisearchpath;
pub mod nistandardallocator;
pub mod nisystem;
pub mod nithread_xenon;
pub mod run_00aa1380;
pub mod run_00aa1de0;
pub mod run_00aa24a0;
pub mod run_00aa2710;
pub mod run_00aa2820;
pub mod run_00aa2ff0;

pub fn funcs(out: &mut Vec<(u32, crate::AbiFn)>) {
    out.extend(bsniallocator::funcs());
    out.extend(nibinarystream::funcs());
    out.extend(nifile::funcs());
    out.extend(nifilename::funcs());
    out.extend(nimemstream::funcs());
    out.extend(nipath::funcs());
    out.extend(nipath_xenon::funcs());
    out.extend(nisearchpath::funcs());
    out.extend(nistandardallocator::funcs());
    out.extend(nisystem::funcs());
    out.extend(nithread_xenon::funcs());
    out.extend(run_00aa1380::funcs());
    out.extend(run_00aa1de0::funcs());
    out.extend(run_00aa24a0::funcs());
    out.extend(run_00aa2710::funcs());
    out.extend(run_00aa2820::funcs());
    out.extend(run_00aa2ff0::funcs());
}
