// Generated by `ledger units` from the files in this folder; do not edit.
#![allow(clippy::module_inception)]

pub mod abstractheap;
pub mod bsblockmemheap;
pub mod bscoremessage;
pub mod bsperformancetimer;
pub mod bsprecisiontimer;
pub mod bsrandom;
pub mod bsreadwritelock;
pub mod bsthread_xenon;
pub mod bstimer;
pub mod memorymanager;
pub mod memorypool;
pub mod oei_io_thread;
pub mod run_00aa43a0;
pub mod run_00aa45a0;
pub mod run_00aa4960;
pub mod run_00aa4d30;
pub mod run_00aa50f0;
pub mod run_00aa5fc0;
pub mod run_00aa6120;
pub mod run_00aa6590;
pub mod run_00aa6680;
pub mod run_00aa7030;
pub mod run_00aa7810;
pub mod run_00aa8ca0;
pub mod scrapheap;
pub mod zerooverheadheap;

pub fn funcs(out: &mut Vec<(u32, crate::AbiFn)>) {
    out.extend(abstractheap::funcs());
    out.extend(bsblockmemheap::funcs());
    out.extend(bscoremessage::funcs());
    out.extend(bsperformancetimer::funcs());
    out.extend(bsprecisiontimer::funcs());
    out.extend(bsrandom::funcs());
    out.extend(bsreadwritelock::funcs());
    out.extend(bsthread_xenon::funcs());
    out.extend(bstimer::funcs());
    out.extend(memorymanager::funcs());
    out.extend(memorypool::funcs());
    out.extend(oei_io_thread::funcs());
    out.extend(run_00aa43a0::funcs());
    out.extend(run_00aa45a0::funcs());
    out.extend(run_00aa4960::funcs());
    out.extend(run_00aa4d30::funcs());
    out.extend(run_00aa50f0::funcs());
    out.extend(run_00aa5fc0::funcs());
    out.extend(run_00aa6120::funcs());
    out.extend(run_00aa6590::funcs());
    out.extend(run_00aa6680::funcs());
    out.extend(run_00aa7030::funcs());
    out.extend(run_00aa7810::funcs());
    out.extend(run_00aa8ca0::funcs());
    out.extend(scrapheap::funcs());
    out.extend(zerooverheadheap::funcs());
}
