// Generated by `ledger units` from the files in this folder; do not edit.
#![allow(clippy::module_inception)]

pub mod algs;
pub mod algs_p2;
pub mod assert;
pub mod binaryfile;
pub mod egmfileio;
pub mod egtfileio_sdk;
pub mod fancontrols;
pub mod fanctlfile;
pub mod lasterror;
pub mod run_00aaf9a0;
pub mod run_00aafa80;
pub mod run_00aafbe0;
pub mod run_00ab0a80;
pub mod run_00ab0d50;
pub mod run_00ab2e70;
pub mod run_00ab3370;
pub mod run_00ab46f0;
pub mod run_00ab9bc0;
pub mod run_00ab9eb0;
pub mod run_00aba3c0;
pub mod run_00ac6220;
pub mod run_00ac68e0;
pub mod trifileio;

pub fn funcs(out: &mut Vec<(u32, crate::AbiFn)>) {
    out.extend(algs::funcs());
    out.extend(algs_p2::funcs());
    out.extend(assert::funcs());
    out.extend(binaryfile::funcs());
    out.extend(egmfileio::funcs());
    out.extend(egtfileio_sdk::funcs());
    out.extend(fancontrols::funcs());
    out.extend(fanctlfile::funcs());
    out.extend(lasterror::funcs());
    out.extend(run_00aaf9a0::funcs());
    out.extend(run_00aafa80::funcs());
    out.extend(run_00aafbe0::funcs());
    out.extend(run_00ab0a80::funcs());
    out.extend(run_00ab0d50::funcs());
    out.extend(run_00ab2e70::funcs());
    out.extend(run_00ab3370::funcs());
    out.extend(run_00ab46f0::funcs());
    out.extend(run_00ab9bc0::funcs());
    out.extend(run_00ab9eb0::funcs());
    out.extend(run_00aba3c0::funcs());
    out.extend(run_00ac6220::funcs());
    out.extend(run_00ac68e0::funcs());
    out.extend(trifileio::funcs());
}
