// Generated by `ledger units` from the files in this folder; do not edit.
#![allow(clippy::module_inception)]

pub mod bsfacegenimage;
pub mod bsfacegenkeyframe;
pub mod bsfacegenmanager;
pub mod bsfacegenmodel;
pub mod bsfacegenmorph;
pub mod bsfacegenmorphdata;
pub mod bsfacegenninode;
pub mod run_0064d880;
pub mod run_0064dbd0;
pub mod run_0064dc30;
pub mod run_0064fcd0;
pub mod run_00658f30;
pub mod run_00659230;
pub mod run_006592c0;
pub mod run_006599d0;
pub mod run_00659ab0;
pub mod run_0065f2b0;
pub mod run_00662760;
pub mod run_00662890;

pub fn funcs(out: &mut Vec<(u32, crate::AbiFn)>) {
    out.extend(bsfacegenimage::funcs());
    out.extend(bsfacegenkeyframe::funcs());
    out.extend(bsfacegenmanager::funcs());
    out.extend(bsfacegenmodel::funcs());
    out.extend(bsfacegenmorph::funcs());
    out.extend(bsfacegenmorphdata::funcs());
    out.extend(bsfacegenninode::funcs());
    out.extend(run_0064d880::funcs());
    out.extend(run_0064dbd0::funcs());
    out.extend(run_0064dc30::funcs());
    out.extend(run_0064fcd0::funcs());
    out.extend(run_00658f30::funcs());
    out.extend(run_00659230::funcs());
    out.extend(run_006592c0::funcs());
    out.extend(run_006599d0::funcs());
    out.extend(run_00659ab0::funcs());
    out.extend(run_0065f2b0::funcs());
    out.extend(run_00662760::funcs());
    out.extend(run_00662890::funcs());
}
