// Generated by `ledger units` from the files in this folder; do not edit.
#![allow(clippy::module_inception)]

pub mod conversation;
pub mod dialogueitem;
pub mod dialogueresponse;
pub mod menutopic;
pub mod run_0083d130;

pub fn funcs(out: &mut Vec<(u32, crate::AbiFn)>) {
    out.extend(conversation::funcs());
    out.extend(dialogueitem::funcs());
    out.extend(dialogueresponse::funcs());
    out.extend(menutopic::funcs());
    out.extend(run_0083d130::funcs());
}
