// Generated by `ledger units` from the files in this folder; do not edit.
#![allow(clippy::module_inception)]

pub mod bssenddebugpage;
pub mod debugtextmanager;
pub mod debugtextscriptprofiler;
pub mod debugtexttexture;

pub fn funcs(out: &mut Vec<(u32, crate::AbiFn)>) {
    out.extend(bssenddebugpage::funcs());
    out.extend(debugtextmanager::funcs());
    out.extend(debugtextscriptprofiler::funcs());
    out.extend(debugtexttexture::funcs());
}
